/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DeliveriesRouteImport } from './routes/deliveries'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as FieldRouteImport } from './routes/field'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as PodRouteImport } from './routes/pod'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as ReceivablesRouteImport } from './routes/receivables'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as SalesRouteImport } from './routes/sales'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesRoute = DeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldRoute = FieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const PodRoute = PodRouteImport.update({
  id: '/pod',
  path: '/pod',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceivablesRoute = ReceivablesRouteImport.update({
  id: '/receivables',
  path: '/receivables',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/clients': typeof ClientsRoute
  '/customers': typeof CustomersRoute
  '/deliveries': typeof DeliveriesRoute
  '/dispatch': typeof DispatchRoute
  '/field': typeof FieldRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRoute
  '/pod': typeof PodRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/receivables': typeof ReceivablesRoute
  '/runs': typeof RunsRoute
  '/sales': typeof SalesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/clients': typeof ClientsRoute
  '/customers': typeof CustomersRoute
  '/deliveries': typeof DeliveriesRoute
  '/dispatch': typeof DispatchRoute
  '/field': typeof FieldRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRoute
  '/pod': typeof PodRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/receivables': typeof ReceivablesRoute
  '/runs': typeof RunsRoute
  '/sales': typeof SalesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/clients': typeof ClientsRoute
  '/customers': typeof CustomersRoute
  '/deliveries': typeof DeliveriesRoute
  '/dispatch': typeof DispatchRoute
  '/field': typeof FieldRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRoute
  '/pod': typeof PodRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/receivables': typeof ReceivablesRoute
  '/runs': typeof RunsRoute
  '/sales': typeof SalesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/clients'
    | '/customers'
    | '/deliveries'
    | '/dispatch'
    | '/field'
    | '/inventory'
    | '/invoices'
    | '/leads'
    | '/login'
    | '/ops'
    | '/pod'
    | '/profile'
    | '/purchases'
    | '/receivables'
    | '/runs'
    | '/sales'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/clients'
    | '/customers'
    | '/deliveries'
    | '/dispatch'
    | '/field'
    | '/inventory'
    | '/invoices'
    | '/leads'
    | '/login'
    | '/ops'
    | '/pod'
    | '/profile'
    | '/purchases'
    | '/receivables'
    | '/runs'
    | '/sales'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/clients'
    | '/customers'
    | '/deliveries'
    | '/dispatch'
    | '/field'
    | '/inventory'
    | '/invoices'
    | '/leads'
    | '/login'
    | '/ops'
    | '/pod'
    | '/profile'
    | '/purchases'
    | '/receivables'
    | '/runs'
    | '/sales'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ClientsRoute: typeof ClientsRoute
  CustomersRoute: typeof CustomersRoute
  DeliveriesRoute: typeof DeliveriesRoute
  DispatchRoute: typeof DispatchRoute
  FieldRoute: typeof FieldRoute
  InventoryRoute: typeof InventoryRoute
  InvoicesRoute: typeof InvoicesRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  OpsRoute: typeof OpsRoute
  PodRoute: typeof PodRoute
  ProfileRoute: typeof ProfileRoute
  PurchasesRoute: typeof PurchasesRoute
  ReceivablesRoute: typeof ReceivablesRoute
  RunsRoute: typeof RunsRoute
  SalesRoute: typeof SalesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries': {
      id: '/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof DeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field': {
      id: '/field'
      path: '/field'
      fullPath: '/field'
      preLoaderRoute: typeof FieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pod': {
      id: '/pod'
      path: '/pod'
      fullPath: '/pod'
      preLoaderRoute: typeof PodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receivables': {
      id: '/receivables'
      path: '/receivables'
      fullPath: '/receivables'
      preLoaderRoute: typeof ReceivablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  ClientsRoute: ClientsRoute,
  CustomersRoute: CustomersRoute,
  DeliveriesRoute: DeliveriesRoute,
  DispatchRoute: DispatchRoute,
  FieldRoute: FieldRoute,
  InventoryRoute: InventoryRoute,
  InvoicesRoute: InvoicesRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  OpsRoute: OpsRoute,
  PodRoute: PodRoute,
  ProfileRoute: ProfileRoute,
  PurchasesRoute: PurchasesRoute,
  ReceivablesRoute: ReceivablesRoute,
  RunsRoute: RunsRoute,
  SalesRoute: SalesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
